/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_gnome_glib_GlibMisc */

#ifndef _Included_org_gnome_glib_GlibMisc
#define _Included_org_gnome_glib_GlibMisc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_gnome_glib_GlibMisc
 * Method:    g_set_prgname
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_gnome_glib_GlibMisc_g_1set_1prgname
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
